### ISSUE TITLE
RelationLine.getDomains() no value

### ISSUE THREAD

**Issue by wliu88** [noon99jaki/pra#3]
Do we need to add a file called _**relations**_ to store query relations? Otherwise the **_Create Queries_** step only generates a **_createQueries.filter_errors_** file without content because **_RelationLine.getDomains()_** is empty.

**Comment by noon99jaki** [comment]
You are right. It expects are list of relations to create query for.

**Comment by wliu88** [comment]
Could you give an example of **_relations_** file? What should be included in this file and what format it should has?

**Comment by noon99jaki** [comment]
Err. I take that back. Looks like it is trying to create queries for all possible relations in a graph:

https://github.com/noon99jaki/pra/blob/69e6c2c16be85df05bafe04fc4bfea1d9b50162a/edu/cmu/pra/SmallJobs.java#L353

**Comment by wliu88** [comment]
The problem is `RelationLine.getDomains()` and `RelationLine.getRanges()` are empty in https://github.com/noon99jaki/pra/blob/8e151fde36d47b2d47d8cf2dde9264341319179f/edu/cmu/pra/SmallJobs.java#L343-L344

This results in the program never enters the for loop in https://github.com/noon99jaki/pra/blob/8e151fde36d47b2d47d8cf2dde9264341319179f/edu/cmu/pra/SmallJobs.java#L353-L355 which actually creates queries.

**Comment by noon99jaki** [comment]
I see. The data was on my home page.
https://github.com/noon99jaki/noon99jaki.github.io/blob/master/data/NELL165.zip

Now I am adding  NELL165 as a sub folder in this repo.
Thanks for the comment.

**Comment by wliu88** [comment]
Thanks for the clarification!
