### ISSUE TITLE
http://www.cs.cmu.edu/~nlao/data/ can not be accessed.

### ISSUE THREAD

**Issue by YerayL** [noon99jaki/pra#8]
Hi, 
    Now, http://www.cs.cmu.edu/~nlao/data/ seems inaccessible. So I don't know how to get the jar file and data files, can you tell me how to solve this problem?

**Comment by noon99jaki** [comment]
Moved all the data files from the homepage to this repo under data/. 
The homepage host server was changed and does not allow direct browse of the folder anymore.

**Comment by YiRuohe** [comment]
Thanks! but I found that http://www.cs.cmu.edu/~nlao/data/pra-src-20140421.jar is also inaccessible. Could you add the jar file to this repo, too?

**Comment by YerayL** [comment]
> Moved all the data files from the homepage to this repo under data/.
> The homepage host server was changed and does not allow direct browse of the folder anymore.

Thanks! but I found that http://www.cs.cmu.edu/~nlao/data/pra-src-20140421.jar is also inaccessible. Could you add the jar file to this repo, too?

**Comment by noon99jaki** [comment]
Updated the path.
https://noon99jaki.github.io/code/2014.pra.zip
