### ISSUE TITLE
Path filtering code in paper "lao2011kb"

### ISSUE THREAD

**Issue by renli1024** [noon99jaki/pra#9]
Thanks first for opening source code for such a good work.

I want to use the path filtering strategies in paper _Random walk inference and learning in a large scale knowledge base_, which in  section _2.3 Data-Driven Path Finding_ and _2.4 Low-Variance Sampling_. Could you provide some instructions to find and use the code implementation of above methods? It's a little hard for me a new beginner to figure out the whole project structure :(

Thanks a lot again!

**Comment by noon99jaki** [comment]
No problem. By default it is low variance sampling `RW_mode=LVParticle`, but you can set it to other approaches defined here
```
public static enum RandomWalkMode {
		Truncate, //Truncation
		Beem, //Beam
		LVWalker, // Sampling (low variance)
		Walker, // Sampling
		Particle, //particle filtering
		LVParticle, //particle filtering (low variance)
		Exact, //none
	}
```
